# File: .github/workflows/ci-cd.yml

name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Install, Lint, Type Check, and Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.jobs
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.10
          cache: 'npm'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci

      - name: Run Linter
        run: npm run Lint

      - name: Run TypeScript Type Check
        run: npm run type-check

      - name: Run Tests with Coverage
        run: npm test -- --Coverage

      - name: Run Security Audit
        run: npm audit --audit-level=high

      - name: Upload Test Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage
          path: coverage/

  notify:
    name: Send Discord Notification
    runs-on: ubuntu-latest
    needs: build-and-test
    if: always()

    steps:
      - name: Send Discord Notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_SECRET }}
        with:
          args: |
            CI/CD Pipeline **${{ github.workflow }}** for **${{ github.repository }}**
            **Status:** ${{ job.status }}
            **Branch:** ${{ github.ref }}
            **Commit:** ${{ github.sha }}
            **Triggered by:** ${{ github.actor }}
            **Run Details:** [View Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
